baseURL = 'https://stampwanker.pages.dev/'
languageCode = 'en-us'
title = 'Stampwanker'
[taxonomies]
bartype = "bartype"
status = "status"
country_name = "country_name"
location = "location"
visa = "visas"
category = "categories"
city_country = "city_country"
